### ISSUE TITLE
syncPath 支持 replaceState

### ISSUE THREAD

**Issue by leeyeh** [taptap/tds-msg-kit#11]
history 有多种 navigate 的 API（pushState / replaceState / go / ...)，但现在的 syncPath 只有一个参数 path，对应的行为是 pushState，如果 client 用了 replaceState 或者 go，server 的浏览器历史记录会与预期的不符。举一些例子：

- server go  `/engine` path，被路由替换为 `/engine/groups/default`，这时候用的是 replace
- 当前路径为 `/resource`，用户点开一个抽屉，push 到 `/resource/details`，用户关闭这个抽屉，这时候应该用 go(-1)

History library 把这些 API [分类成了三类 action](https://github.com/remix-run/history/blob/main/docs/api-reference.md#action)：Pop / Push / Replace，这个抽象覆盖了所有 API，我们可以在 syncPath 协议层面沿用这个抽象。具体到 API 层面，可以在 syncPath API 里加上新的可选参数 action 来覆盖 replace 的问题：
```ts
syncPath: (path: string, options: { action: 'push' | 'replace' }): void
```

Pop 则要稍微复杂一些，因为 pop 不需要 path，而是一个 number 类型的 offset，更 syncPath 不太兼容，可能可以搞一个新的方法。当然也可以暂时先不考虑。

**Comment by iceprosurface** [comment]
如果要按照完整的 history api 设计的话，感觉要不 override 一下 syncPath 方法让他同时支持不同种类的，方便以后扩展。
比如这样：

```ts
syncPath: (options: { action: 'go' | 'back', delta?: number  } |  { action: 'push' | 'replace', path: string } | { action: 'forward' } | ...etc): void
syncPath: (path: string, options: { action: 'push' | 'replace' }): void
```
